networks:
  network-napolitech:
    driver: bridge
  redis-net:
    driver: bridge

services:
  backend:
    image: napolitech/backend-napolitech-dev:1.1.0
    container_name: backend-napolitech
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_APPLICATION_NAME: back-end-napolitech

      DATASOURCE_URL: jdbc:mysql://db:3306/pizzaria_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      DATASOURCE_USERNAME: napolitech
      DATASOURCE_PASSWORD: napolitech_dev
      DATASOURCE_DRIVER: com.mysql.cj.jdbc.Driver

      SERVER_PORT: 8080

      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USERNAME: mailsendernoreplyv8@gmail.com
      MAIL_PASSWORD: gycihyclbdscmhor
      MAIL_SMTP_AUTH: true
      MAIL_SMTP_STARTTLS: true

      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: napolitech
      BROKER_EXCHANGE_NAME: napolitech-exchange
      BROKER_QUEUE_NAME: pedidos-queue
      BROKER_ROUTING_KEY: pedidos-routing-key
      REDIS_HOST: redis

    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - network-napolitech
      - redis-net

  db:
    image: mysql:8.0
    container_name: mysql-napolitech
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: pizzaria_db
      MYSQL_USER: napolitech
      MYSQL_PASSWORD: napolitech_dev
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u$$MYSQL_USER -p$$MYSQL_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - network-napolitech

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq-napolitech
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: napolitech
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl node_health_check"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s
    networks:
      - network-napolitech

  redis:
    image: redis:7-alpine
    container_name: redis
    command:
      [
        "redis-server",
        "--maxmemory", "512mb",
        "--maxmemory-policy", "allkeys-lfu",
        "--save", "60", "1",
        "--loglevel", "warning"
      ]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - redis-net
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping || exit 1" ]
      interval: 10s
      timeout: 2s
      retries: 5
      start_period: 10s

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    depends_on:
      - redis
    networks:
      - redis-net
    volumes:
      - redisinsight_data:/data

volumes:
  mysql_data:
  rabbitmq_data:
  redis_data:
  redisinsight_data:
