networks:
  network-napolitech:
    driver: bridge

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-napolitech
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_APPLICATION_NAME: back-end-napolitech

      DATASOURCE_URL: jdbc:mysql://db:3306/pizzaria_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      DATASOURCE_USERNAME: napolitech
      DATASOURCE_PASSWORD: napolitech_dev
      DATASOURCE_DRIVER: com.mysql.cj.jdbc.Driver

      SERVER_PORT: 8080

      LOGGING_SQL: DEBUG
      LOGGING_BINDER: TRACE

      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USERNAME: mailsendernoreplyv8@gmail.com
      MAIL_PASSWORD: gycihyclbdscmhor
      MAIL_SMTP_AUTH: true
      MAIL_SMTP_STARTTLS: true

      # RabbitMQ
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: napolitech
      BROKER_EXCHANGE_NAME: napolitech-exchange
      BROKER_QUEUE_NAME: pedidos-queue
      BROKER_ROUTING_KEY: pedidos-routing-key

    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - network-napolitech

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: pizzaria_db
      MYSQL_USER: napolitech
      MYSQL_PASSWORD: napolitech_dev
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - network-napolitech

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: backend-napolitech-rabbitmq-1
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: napolitech
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - network-napolitech
